#
# Copyright 2018 Freescale Semiconductor
# Copyright 2024 Josua Mayer <josua@solid-run.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += lx2160a.o
obj-y += ddr.o
obj-$(CONFIG_TARGET_LX2160ACEX7) += eth_lx2160acex7.o
obj-y += serdes.o
